name: Integration Test (Python zeroconf)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install our MSRV
      uses: dtolnay/rust-toolchain@stable
      with:
         toolchain: "1.74"

    - name: Compile example
      run: cargo build --example register

    - name: Install dependencies
      run: |
        sudo apt-get -y install python3-setuptools python3-wheel
        pip3 install --user zeroconf

    - name: Test zeroconf
      run: |
        timeout 5 cargo run --example register &
        python3 examples/zeroconf_test.py
